language: python
python:
  - "2.7"
# command to install dependencies
install:
  - pip install -r requirements.txt --use-mirrors
  - pip install nose coverage
# command to run tests
script: nosetests funnel tests
notifications:
  email: false
  irc: "irc.freenode.net#hasgeek-dev"
